### ISSUE TITLE
custom font

### ISSUE THREAD

**Issue by jjhesk** [binaryfork/Spanny#1]
does it support custom fonts?

**Comment by jjhesk** [comment]
i use this [component](https://github.com/HKMOpen/PixlUI)

**Comment by binaryfork** [comment]
I'm not sure if it will work with PixlUI. However Spanny supports all spannables and you can make your own Spannable with a custom font, example: http://stackoverflow.com/questions/4819049/how-can-i-use-typefacespan-or-stylespan-with-a-custom-typeface

You can also use https://github.com/chrisjenx/Calligraphy to make a custom TextAppearance style with a custom font and provide it to TextAppearanceSpan.

**Comment by binaryfork** [comment]
I've added example how to use custom font with Spanny.
