### ISSUE TITLE
library concern

### ISSUE THREAD

**Issue by MohamadAtieh** [binaryfork/Spanny#3]
Hey! I came by your project a while ago and thought that I had to implement something similar to my Reddit client app. It appears you starred my [project](https://github.com/Redgram/redgram-for-reddit) and I was wondering how compatible is Spanny with Reddit's formatted text? 

If yes, do you mind if I forked it and extended it with more features? 

Thanks.

**Edit:** I see it's just one small class. I was thinking of supporting the formatting on Reddit. Do you think it's doable?

**Comment by binaryfork** [comment]
Hi! Reddit is using [markdown](https://en.wikipedia.org/wiki/Markdown) for formatting so I think what you need is to convert the reddit's markdown text to a spannable. You can use [bypass](http://uncodin.github.io/bypass/) or something similar for this or write your own.

Feel free to fork and add features if you need.
